### ISSUE TITLE
Fungi in ModelSEED

### ISSUE THREAD

**Issue by lisakmalins** [ModelSEED/ModelSEED-UI#163]
Hello ModelSEED Team,

I was excited to read in the [2021 ModelSEED paper](https://doi.org/10.1093/nar/gkaa746) that plants, fungi, and microbes are included in the tool because I have a fungal genome that I'm working on. However, in the web interface at <https://modelseed.org/>, the only choices are "plants" or "microbes."

Are fungi supported in the live version of the ModelSEED server? Which of the two options should I choose for a fungal genome?

Thank you for your time!

Lisa Malins

**Comment by samseaver** [comment]
Hello Lisa, thank you for your interest in ModelSEED.

I'm looping in my colleague @janakagithub here with respect to Fungi because Janaka has been working with this kingdom.

As it happens, the ModelSEED Biochemistry paper we published was _only_ for the biochemistry, and the work did not include the annotation of genomes, for any species (the microbes and plants options were released as part of earlier published papers). Rather, when publishing the biochemistry paper, we meant that we have biochemical pathways that are specific to fungi. Again, this did not mean that the paper included the curation of fungal enzymes.

Thanks
Sam Seaver

**Comment by lisakmalins** [comment]
Hi Sam,

Thank you so much for the reply!

I see, I misunderstood that nuance. So right now, metabolic modeling of fungal genomes is not supported in the ModelSEED web tool? Are there plans to build that functionality in the future?

Best,
Lisa Malins

**Comment by janakagithub** [comment]
Hi Lisa, 
Thank you for your interest. 
While we have the Fungal biochemistry as part of the ModelSEED biochemistry repo, the fungal model construction pipeline has been implemented in DOE KBase ([www.kbase.us](http://www.kbase.us/)). Once you sign up for a KBase account (https://narrative.kbase.us/#signup), you will be able to use the platform for a variety of analyses. Fungal genomes can be uploaded into the system to construct metabolic models using the 'Build Fungal Model' app. Additionally, you will have the ability to annotate Fungal genomes using the DRAM annotation pipeline (App - Annotate and Distill Genomes with DRAM). Please let me know ([janakae@anl.gov](mailto:janakae@anl.gov)) if you have any questions or need further guidance. I am happy to help.

Best, 
Janaka

**Comment by lisakmalins** [comment]
Hi Janaka and Sam,

Thank you so much for your help! I'll pitch KBase to my team. Thanks for your time!

Best,
Lisa Malins
